name: turnip-release-armhf

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  branch_version: "24.3"

jobs:
  start_building_turnip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
        sudo apt update
        sudo apt build-dep mesa -y
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build patchelf unzip curl python3-pip flex bison zip git dpkg-dev debhelper pkg-config docker.io
        sudo apt-get remove containerd
        sudo apt-get install containerd.io
        sudo apt-get install -y --reinstall containerd.io
        sudo apt-get install -y --reinstall containerd
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-mark unhold containerd
        sudo apt-get update
        sudo apt-get install containerd.io

    - name: Install or Upgrade Meson
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade meson

    - name: Create Work Directory
      run: mkdir -p turnip_workdir

    - name: Download and Extract Android NDK
      run: |
        cd turnip_workdir
        ndkver="android-ndk-r26c"
        if [ ! -d "$ndkver" ]; then
          curl -LO https://dl.google.com/android/repository/"$ndkver"-linux.zip
          unzip "$ndkver"-linux.zip
        fi

    - name: Clone Mesa Source
      run: |
        cd turnip_workdir
        git clone --depth=1 --branch ${{ env.branch_version }} https://gitlab.freedesktop.org/mesa/mesa.git

    - name: Clone and Apply Patches
      run: |
        cd turnip_workdir
        git clone https://github.com/MastaG/mesa-turnip-ppa.git mesa-turnip
        cd mesa
        for patch in $GITHUB_WORKSPACE/turnip_workdir/mesa-turnip/turnip-patches/*.patch; do
          git apply "$patch"
        done

    - name: Build Mesa for Android (32-bit)
      run: |
        cd turnip_workdir/mesa
        ndk="$PWD/../android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin"
        cat <<EOF > "android-arm"
        [binaries]
        ar = '$ndk/llvm-ar'
        c = ['ccache', '$ndk/armv7a-linux-androideabi31-clang']
        cpp = ['ccache', '$ndk/armv7a-linux-androideabi31-clang++']
        c_ld = 'lld'
        cpp_ld = 'lld'
        strip = '$ndk/arm-linux-androideabi-strip'
        [host_machine]
        system = 'android'
        cpu_family = 'arm'
        cpu = 'armv7'
        endian = 'little'
        EOF
        mkdir -p build-android-arm
        meson setup build-android-arm --cross-file "$PWD/android-arm" \
            -Dbuildtype=release -Dplatforms=android -Dplatform-sdk-version=31 \
            -Dvulkan-drivers=freedreno -Dvulkan-beta=true -Dfreedreno-kmds=kgsl -Db_lto=true
        ninja -C build-android-arm

    - name: Patchelf and Package
      run: |
        cd turnip_workdir/mesa/build-android-arm/src/freedreno/vulkan
        cp libvulkan_freedreno.so "$GITHUB_WORKSPACE/turnip_workdir"
        cd "$GITHUB_WORKSPACE/turnip_workdir"
        patchelf --set-soname vulkan.adreno.so libvulkan_freedreno.so
        mv libvulkan_freedreno.so vulkan.ad07XX.so
        mkdir -p turnip_${{ env.branch_version }}/usr/local/lib
        cp vulkan.ad07XX.so turnip_${{ env.branch_version }}/usr/local/lib
        mkdir -p turnip_${{ env.branch_version }}/DEBIAN
        cat <<EOL > turnip_${{ env.branch_version }}/DEBIAN/control
        Package: turnip
        Version: ${{ env.branch_version }}
        Architecture: armhf, arm
        Maintainer: sabamdarif
        Description: Vulkan driver for Freedreno and Android (32-bit)
        EOL
        dpkg-deb --build turnip_${{ env.branch_version }}

    # Build RPM in Fedora Docker
    - name: Build RPM in Fedora Docker
      run: |
        docker run --rm -v $PWD:/workspace fedora:latest bash -c "
          cd /workspace &&
          dnf install -y rpm-build &&
          rpmbuild -bb turnip.spec"  # Make sure you have a valid 'turnip.spec' file

    # Build Arch Package in Arch Docker
    - name: Build Arch Package in Arch Docker
      run: |
        docker run --rm -v $PWD:/workspace archlinux:latest bash -c "
          cd /workspace &&
          makepkg -si"  # Make sure your PKGBUILD file is in the workspace

    # Build Alpine Package in Alpine Docker
    - name: Build Alpine Package in Alpine Docker
      run: |
        docker run --rm -v $PWD:/workspace alpine:latest bash -c "
          apk add --no-cache abuild &&
          cd /workspace &&
          abuild -r"  # Make sure you have a valid abuild config

    - name: Upload To Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ github.workspace }}/turnip_workdir/turnip_${{ env.branch_version }}.deb
          ${{ github.workspace }}/turnip_workdir/turnip_${{ env.branch_version }}.rpm
          ${{ github.workspace }}/turnip_workdir/turnip_${{ env.branch_version }}-*.pkg.tar.zst
          ${{ github.workspace }}/turnip_workdir/turnip_${{ env.branch_version }}-*.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        name: turnip android arm
        tag_name: mesa_turnip_${{ env.branch_version }}_arm
        draft: false
        prerelease: false