name: turnip-release

on:
  workflow_dispatch:
  schedule:
  - cron: '30 2 * * *'

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
        sudo apt update
        sudo apt build-dep mesa -y
    
    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa/build-android-aarch64/meson-logs/meson-log.txt
    
    - id: versions
      name: "Get release info"
      run: |
        echo "name=$(cat turnip_workdir/release)" >> "$GITHUB_OUTPUT"
        echo "tag=$(cat turnip_workdir/tag)" >> "$GITHUB_OUTPUT"
        echo "filename=$(cat turnip_workdir/filename)" >> "$GITHUB_OUTPUT"
        echo "patched=$(cat turnip_workdir/patched)" >> "$GITHUB_OUTPUT"

    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body_path: turnip_workdir/description
        name: ${{ steps.versions.outputs.name }}
        tag_name: ${{ steps.versions.outputs.tag }}
        files: |
           turnip_workdir/${{ steps.versions.outputs.filename }}.zip

    - name: Build .deb package for "turnip" with patched
      if: ${{ contains(steps.versions.outputs.patched, 'true') }}
      run: |
        cd turnip_workdir
        # Assuming a package building script exists or use dpkg-deb or another tool to build the deb
        dpkg-buildpackage -us -uc -b
        # Move the generated .deb file to a known location
        mv ../*.deb ./turnip_workdir/${{ steps.versions.outputs.filename }}_patched.deb

    - name: Release "turnip" with patched .deb
      if: ${{ contains(steps.versions.outputs.patched, 'true') }}
      uses: softprops/action-gh-release@v1
      with:
        body_path: turnip_workdir/description
        name: ${{ steps.versions.outputs.name }}
        tag_name: ${{ steps.versions.outputs.tag }}
        files: |
          turnip_workdir/${{ steps.versions.outputs.filename }}_patched.deb
