name: turnip-release-aarch64

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  branch_version: "24.3"

jobs:
  start_building_turnip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/g' /etc/apt/sources.list.d/*.sources
        sudo apt update
        sudo apt build-dep mesa -y
    
    - name: Install Dependencies
      run: |
        sudo apt-get install -y meson ninja-build patchelf unzip curl python3-pip flex bison zip git dpkg-dev debhelper pkg-config

    - name: Install or Upgrade Meson
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade meson

    - name: Create Work Directory
      run: mkdir -p turnip_workdir

    - name: Download and Extract Android NDK
      run: |
        cd turnip_workdir
        ndkver="android-ndk-r26c"
        if [ ! -d "$ndkver" ]; then
          curl -LO https://dl.google.com/android/repository/"$ndkver"-linux.zip
          unzip "$ndkver"-linux.zip
        fi

    - name: Clone Mesa Source
      run: |
        cd turnip_workdir
        git clone --depth=1 --branch ${{ env.branch_version }} https://gitlab.freedesktop.org/mesa/mesa.git

    - name: Clone and Apply Patches
      run: |
        cd $GITHUB_WORKSPACE/turnip_workdir
        git clone https://github.com/MastaG/mesa-turnip-ppa.git mesa-turnip
        cd mesa
        for patch in $GITHUB_WORKSPACE/turnip_workdir/mesa-turnip/turnip-patches/*.patch; do
          git apply "$patch"
        done

    - name: Build Mesa for Android
      run: |
        cd turnip_workdir/mesa
        ndk="$PWD/../android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin"
        cat <<EOF > "android-aarch64"
        [binaries]
        ar = '$ndk/llvm-ar'
        c = ['ccache', '$ndk/aarch64-linux-android31-clang']
        cpp = ['ccache', '$ndk/aarch64-linux-android31-clang++']
        c_ld = 'lld'
        cpp_ld = 'lld'
        strip = '$ndk/aarch64-linux-android-strip'
        [host_machine]
        system = 'android'
        cpu_family = 'aarch64'
        cpu = 'armv8'
        endian = 'little'
        EOF
        mkdir -p build-android-aarch64
        meson setup build-android-aarch64 --cross-file "$PWD/android-aarch64" \
            -Dbuildtype=release -Dplatforms=android -Dplatform-sdk-version=31 \
            -Dvulkan-drivers=freedreno -Dvulkan-beta=true -Dfreedreno-kmds=kgsl -Db_lto=true
        ninja -C build-android-aarch64

    - name: Package Mesa
      run: |
        cd turnip_workdir/mesa/build-android-aarch64/src/freedreno/vulkan
        cp libvulkan_freedreno.so "$GITHUB_WORKSPACE/turnip_workdir"
        cd "$GITHUB_WORKSPACE/turnip_workdir"
        patchelf --set-soname vulkan.adreno.so libvulkan_freedreno.so
        mv libvulkan_freedreno.so vulkan.ad07XX.so
        mkdir -p turnip_${{ env.branch_version }}/usr/local/lib
        cp vulkan.ad07XX.so turnip_${{ env.branch_version }}/usr/local/lib
        mkdir -p turnip_${{ env.branch_version }}/DEBIAN
        cat <<EOL > turnip_${{ env.branch_version }}/DEBIAN/control
        Package: turnip
        Version: ${{ env.branch_version }}
        Architecture: arm64
        Maintainer: sabamdarif
        Description: Vulkan driver for Freedreno and Android
        EOL
        dpkg-deb --build turnip_${{ env.branch_version }}

    - name: Upload To Releases
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/turnip_workdir/turnip_${{ env.branch_version }}.deb
        token: ${{ secrets.GITHUB_TOKEN }}
        name: turnip android
        tag_name: mesa_turnip_${{ env.branch_version }}
        draft: false
        prerelease: false